name: build
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
      - /refs/heads/master

jobs:
  it:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: |
          npm install

      - name: build
        run: |
          npm run build

      - name: lint
        run: |
          npm run lint

      - name: test
        run: |
          npm run test

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
