name: check
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      # - name: golang
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.17

 
      # - name: go get tools
      #   run: |
      #     go get golang.org/x/lint/golint
    
      - name: go build
        run: |
          go build ./...
    
      - name: go vet
        run: |
          go vet ./...
  
      # - name: golint
      #   run: |
      #     golint ./...

      - name: go test
        run: |
          go test -v -coverprofile=profile.cov ./...
        env:
          ## Note: GOPATH mandatory otherwise CDK fails to build lambda
          GOPATH: /home/runner/work/scud/go

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
